In [ ]:
import numpy as np

In [ ]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([1,2,3,4])

print(arr[0])
print(arr[-1])
print(arr[0:2])

1
4
[1 2]


In [ ]:
arr = np.array([[1,2,3], [6,7,8]])
print("1st row: ", arr[0, :])
print("1st col: ", arr[:, 0])
print("second element in first row: ", arr[0, 1])

#arr[rows, cols]

#mxn matrix: m rows, n columns

1st row:  [1 2 3]
1st col:  [1 6]
second element in first row:  2


In [ ]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])
print(arr[1:])
print(arr[:5])
print(arr[1:-2])
print(arr[1:5:2]) #step size 2

[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4 5]
[2 3 4 5]
[2 4]


In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

new_arr = np.concatenate((arr1,arr2), axis = 1) #concatenates in column dimension
print(new_arr)

new_arr = np.concatenate((arr1,arr2), axis = 0) #concatenates in row dimension
print(new_arr)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


minw ||y - Xw||^2 = minw ||y - y pred||^2

X is the feature matrix - includes features of sample
w is the unknown value (model weight vector)
y is the known value

Xw = y pred

default vector is a column vector

In [ ]:
house1 = np.array([3,1,1180,5650,1])
house2 = np.array([3,2,1680,8080,1])

print("house 1: {}".format(house1))
print("house 2: {}".format(house2))

#addition/subtraction - matrices must have the same size
print("house1 + house2: {}".format(house1 + house2))
print("house1 - house2: {}".format(house1 - house2))

house 1: [   3    1 1180 5650    1]
house 2: [   3    2 1680 8080    1]
house1 + house2: [    6     3  2860 13730     2]
house1 - house2: [    0    -1  -500 -2430     0]


In [ ]:
# vector multiplication: scalar, elementwise, inner product

#1. Scalar multiplication
house1 = np.array([3,1,1180,5650,1])

print("house1: {}".format(house1))
print("2*house1: {}".format(house1*2))

house1: [   3    1 1180 5650    1]
2*house1: [    6     2  2360 11300     2]


In [ ]:
#2. Element-wise multiplication

house1 = np.array([3,1,1180,5650,1])
house2 = np.array([3,2,1680,8080,1])

print("house1 X house2: {}".format(np.multiply(house1,house2)))

house1 X house2: [       9        2  1982400 45652000        1]


In [ ]:
#3. Inner product (use for Xw)

house1 = np.array([3,1,1180,5650,1])
house2 = np.array([3,2,1680,8080,1])

print("inner product: {}".format(np.inner(house1, house2)))

inner product: 47634412


In [ ]:
#vector norm - magnitude of a vector

#l1 norm: ||x||1 = |x1| + |x2| + ... + |xn|
#l2 norm (euclidean norm): ||x||2 = sqrt(x1^2 + x2^2 + ... +xn^2)
#l infinity norm (Max-norm): ||x||inf = max 1<=i<=d |xi|

x = np.array([1,2,3,4])

print("l1-norm: {}".format(np.linalg.norm(x, ord=1)))
print("l2-norm: {}".format(np.linalg.norm(x, ord=2)))
print("linf-norm: {}".format(np.linalg.norm(x, ord=np.inf)))

l1-norm: 10.0
l2-norm: 5.477225575051661
linf-norm: 4.0


In [ ]:
x = np.array([1,-2,2,0])

print("l1-norm: {}".format(np.linalg.norm(x, ord=1)))
print("l2-norm: {}".format(np.linalg.norm(x, ord=2)))
print("linf-norm {}".format(np.linalg.norm(x,ord=np.inf)))

l1-norm: 5.0
l2-norm: 3.0
linf-norm 2.0


In [ ]:
import numpy as np

x = np.array([-4,-3,2,1])

print("l1-norm: {}".format(np.linalg.norm(x, ord=1)))
print("l2-norm: {}".format(np.linalg.norm(x, ord=2)))
print("linf-norm {}".format(np.linalg.norm(x,ord=np.inf)))

l1-norm: 10.0
l2-norm: 5.477225575051661
linf-norm 4.0


In [ ]:
#orthogonality
#orthogonal if inner product = 0

In [ ]:
#transposition
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.transpose(A)

print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

**Gradient descent**

> decrease the loss function along the direction of the negative gradient

x1 = x - n(grad(f(x)) ; n = learning rate

Lin Regress: minw||y - Xw||^2

Gradient: -2X^T(y-Xw)

Gradient descent: w_t+1 = w_t - n(2X^T(Xw_t-y))