# 1. Example

**1.1 Load data with pandas**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
from google.colab import files
uploaded = files.upload()

Saving cars.csv to cars.csv


In [1]:
import numpy as np
import pandas as pd

In [7]:
#Load data with pandas
df = pd.read_csv("cars.csv")
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0         130   
1            Buick Skylark 320  15.0          8         350.0         165   
2           Plymouth Satellite  18.0          8         318.0         150   
3                AMC Rebel SST  16.0          8         304.0         150   
4                  Ford Torino  17.0          8         302.0         140   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0          86   
402          Volkswagen Pickup  44.0          4          97.0          52   
403              Dodge Rampage  32.0          4         135.0          84   
404                Ford Ranger  28.0          4         120.0          79   
405                 Chevy S-10  31.0          4         119.0          82   

     Weight  Acceleration  Model  Origin  
0      3504          12.0     70

In [8]:
#Convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


**1.2 Operation for vector**

In [9]:
#Get the first row and the second to last row
x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

#Addition
y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


**1.3 Operation for matrix**

In [10]:
#Get first 5 rows and last 5 rows
m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


# 2. Task

**2.1 Get the first column and the second to last column from X**

In [11]:
col1 = X[:, 0]
col2 = X[:, -2]

print(col1)
print(col2)

[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0 0.0 0.0 0.0 0.0 0.0
 15.0 14.0 0.0 15.0 14.0 24.0 22.0 18.0 21.0 27.0 26.0 25.0 24.0 25.0 26.0
 21.0 10.0 10.0 11.0 9.0 27.0 28.0 25.0 25.0 0.0 19.0 16.0 17.0 19.0 18.0
 14.0 14.0 14.0 14.0 12.0 13.0 13.0 18.0 22.0 19.0 18.0 23.0 28.0 30.0
 30.0 31.0 35.0 27.0 26.0 24.0 25.0 23.0 20.0 21.0 13.0 14.0 15.0 14.0
 17.0 11.0 13.0 12.0 13.0 19.0 15.0 13.0 13.0 14.0 18.0 22.0 21.0 26.0
 22.0 28.0 23.0 28.0 27.0 13.0 14.0 13.0 14.0 15.0 12.0 13.0 13.0 14.0
 13.0 12.0 13.0 18.0 16.0 18.0 18.0 23.0 26.0 11.0 12.0 13.0 12.0 18.0
 20.0 21.0 22.0 18.0 19.0 21.0 26.0 15.0 16.0 29.0 24.0 20.0 19.0 15.0
 24.0 20.0 11.0 20.0 21.0 19.0 15.0 31.0 26.0 32.0 25.0 16.0 16.0 18.0
 16.0 13.0 14.0 14.0 14.0 29.0 26.0 26.0 31.0 32.0 28.0 24.0 26.0 24.0
 26.0 31.0 19.0 18.0 15.0 15.0 16.0 15.0 16.0 14.0 17.0 16.0 15.0 18.0
 21.0 20.0 13.0 29.0 23.0 20.0 23.0 24.0 25.0 24.0 18.0 29.0 19.0 23.0
 23.0 22.0 25.0 33.0 28.0 25.0 25.0 26.0 27.0 17.5 16.0 15.5 14.5 22.0

**2.2 Perform the following operations on the vectors and print the result**

In [12]:
# 1. addition and subtraction
add = col1 + col2
sub = col1 - col2

print(add)
print(sub)

[30.0 26.5 29.0 28.0 27.5 25.0 23.0 22.5 24.0 23.5 17.5 11.5 11.0 10.5
 11.0 25.0 22.0 8.0 24.5 24.0 39.0 37.5 33.5 37.0 41.5 46.5 42.5 38.5 42.5
 38.5 36.0 24.0 25.0 24.5 27.5 41.5 43.5 39.0 44.0 20.0 32.0 31.5 32.5
 34.5 33.5 26.0 25.5 27.5 27.0 23.5 25.0 25.0 31.5 41.0 34.0 32.5 37.0
 42.0 49.5 44.5 50.0 53.0 46.0 46.5 39.5 42.0 46.5 39.5 37.5 25.0 26.0
 28.5 27.0 28.5 22.0 26.5 25.5 25.5 32.5 27.5 27.0 29.0 28.0 32.5 40.0
 40.5 44.0 38.0 45.0 37.5 43.0 43.5 26.0 25.5 26.0 28.5 27.5 23.5 25.0
 26.0 28.5 24.0 23.0 24.0 34.5 34.0 34.0 34.5 39.0 47.0 25.0 24.5 26.0
 24.5 33.0 39.0 40.5 38.5 31.5 37.5 35.0 41.5 28.0 25.5 48.5 39.5 34.0
 34.5 26.0 38.0 33.5 22.0 36.5 38.0 35.0 32.0 50.0 42.5 53.0 42.0 33.0
 34.0 34.5 30.0 27.5 27.5 30.0 29.5 45.5 41.5 40.5 47.5 51.0 42.5 39.5
 40.0 39.0 41.5 47.0 35.0 34.0 36.0 34.5 27.5 29.0 30.5 27.5 38.0 34.5
 34.0 37.0 36.0 33.5 25.0 45.0 40.0 36.0 41.5 37.5 41.5 41.0 32.5 43.0
 36.0 38.0 40.0 36.5 38.5 50.5 43.5 41.9 39.9 43.7 42.3 30.5 29.0 29.4
 2

In [13]:
# 2. element-wise multiplication
mul = np.multiply(col1, col2)

print(mul)

[216.0 172.5 198.0 192.0 178.5 150.0 126.0 119.0 140.0 127.5 0.0 0.0 0.0
 0.0 0.0 150.0 112.0 0.0 142.5 140.0 360.0 341.0 279.0 336.0 391.5 533.0
 437.5 348.0 437.5 325.0 315.0 140.0 150.0 148.5 166.5 391.5 434.0 350.0
 475.0 0.0 247.0 248.0 263.5 294.5 279.0 168.0 161.0 189.0 182.0 138.0
 156.0 156.0 243.0 418.0 285.0 261.0 322.0 392.0 585.0 435.0 589.0 630.0
 513.0 533.0 372.0 425.0 540.5 390.0 346.5 156.0 168.0 202.5 182.0 195.5
 121.0 175.5 162.0 162.5 256.5 187.5 182.0 208.0 196.0 261.0 396.0 409.5
 468.0 352.0 476.0 333.5 420.0 445.5 169.0 161.0 169.0 203.0 187.5 138.0
 156.0 169.0 203.0 143.0 132.0 143.0 297.0 288.0 288.0 297.0 368.0 546.0
 154.0 150.0 169.0 150.0 270.0 380.0 409.5 363.0 243.0 351.5 294.0 403.0
 195.0 152.0 565.5 372.0 280.0 294.5 165.0 336.0 270.0 121.0 330.0 357.0
 304.0 255.0 589.0 429.0 672.0 425.0 272.0 288.0 297.0 224.0 188.5 189.0
 224.0 217.0 478.5 403.0 377.0 511.5 608.0 406.0 372.0 364.0 360.0 403.0
 496.0 304.0 288.0 315.0 292.5 184.0 210.0 232.0 189.

In [14]:
# 3. inner product
inner = np.inner(col1, col2)

print(inner)

149295.04000000004


In [15]:
# 4. three norms
from numpy import linalg as la

#Col1
norm_l1_col1 = la.norm(col1, ord=1)
norm_l2_col1 = la.norm(col1, ord=2)
norm_linf_col1 = la.norm(col1, ord=np.inf)

print(norm_l1_col1)
print(norm_l2_col1)
print(norm_linf_col1)

#Col2

norm_l1_col2 = la.norm(col2, ord=1)
norm_l2_col2 = la.norm(col2, ord=2)
norm_linf_col2 = la.norm(col2, ord=np.inf)

print(norm_l1_col2)
print(norm_l2_col2)
print(norm_linf_col2)

9358.800000000003
494.28813459357895
46.6
6300.999999999994
317.7616716975161
24.8


In [16]:
# 5. compute the distance between the two vectors
d = la.norm(col1 - col2, ord=2)

print(d)

216.10913909411607


**2.3 Get the first 3 columns and the last 3 columns from X**

In [17]:
A = X[:, 0:3]
B = X[:, -3:]

print(A)
print(B)

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 ...
 [32.0 4 135.0]
 [28.0 4 120.0]
 [31.0 4 119.0]]
[[3504 12.0 70]
 [3693 11.5 70]
 [3436 11.0 70]
 ...
 [2295 11.6 82]
 [2625 18.6 82]
 [2720 19.4 82]]


**2.4 Perform the following operations on the matrices and print the result**

In [18]:
# 1. addition and subtraction
add = A + B
sub = A - B

print(add)
print(sub)

[[3522.0 20.0 377.0]
 [3708.0 19.5 420.0]
 [3454.0 19.0 388.0]
 ...
 [2327.0 15.6 217.0]
 [2653.0 22.6 202.0]
 [2751.0 23.4 201.0]]
[[-3486.0 -4.0 237.0]
 [-3678.0 -3.5 280.0]
 [-3418.0 -3.0 248.0]
 ...
 [-2263.0 -7.6 53.0]
 [-2597.0 -14.600000000000001 38.0]
 [-2689.0 -15.399999999999999 37.0]]


In [21]:
# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = np.transpose(B)

print(C)
print(np.shape(C))

[[3504 3693 3436 ... 2295 2625 2720]
 [12.0 11.5 11.0 ... 11.6 18.6 19.4]
 [70 70 70 ... 82 82 82]]
(3, 406)


In [22]:
# 3. compute the product between A and C, and print the result and its shape
AC = np.dot(A,C)

print(AC)
print(np.shape(AC))

[[84658.0 88056.0 83426.0 ... 66576.8 72572.8 74289.2]
 [77156.0 79987.0 76128.0 ... 63217.8 68223.8 69655.2]
 [85428.0 88826.0 84196.0 ... 67478.8 73474.8 75191.2]
 ...
 [121626.0 127672.0 119446.0 ... 84556.4 95144.4 98187.6]
 [106560.0 111850.0 104652.0 ... 74146.4 83414.4 86077.6]
 [117002.0 122859.0 114890.0 ... 80949.4 91207.4 94155.6]]
(406, 406)


In [23]:
# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = np.transpose(A)

print(D)
print(np.shape(D))

[[18.0 15.0 18.0 ... 32.0 28.0 31.0]
 [8 8 8 ... 4 4 4]
 [307.0 350.0 318.0 ... 135.0 120.0 119.0]]
(3, 406)


In [24]:
# 5. compute the product between D and B, and print the result and its shape
BD = np.dot(B,D)

print(BD)
print(np.shape(BD))

[[84658.0 77156.0 85428.0 ... 121626.0 106560.0 117002.0]
 [88056.0 79987.0 88826.0 ... 127672.0 111850.0 122859.0]
 [83426.0 76128.0 84196.0 ... 119446.0 104652.0 114890.0]
 ...
 [66576.8 63217.8 67478.8 ... 84556.4 74146.4 80949.4]
 [72572.8 68223.8 73474.8 ... 95144.4 83414.4 91207.4]
 [74289.2 69655.2 75191.2 ... 98187.6 86077.6 94155.6]]
(406, 406)
